on:
  workflow_call:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      # production mode
      - name: Build Production
        uses: docker/build-push-action@v6
        with:
          file: docker/node.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: "pocket-network/pocketdex:production"
          build-args: |
            CI=true
            NODE_ENV=production
            ENDPOINT=http://proxy:26657
            CHAIN_ID=poktroll

      # develop mode
      - name: Build Develop
        uses: docker/build-push-action@v6
        with:
          file: docker/node.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          tags: "pocket-network/pocketdex:test"
          # NODE_ENV=test & NODE_ENV=development result on the same build image due to install dependencies.
          build-args: |
            CI=true
            NODE_ENV=test
            ENDPOINT=http://proxy:26657
            CHAIN_ID=poktroll

      - name: Run tests in Docker container
        # TODO: remove this line when the test are fixed
        # Right now there is an extraneous issue:
        # Cause: Error: Cannot read properties of undefined (reading 'length')
        env:
          CHAIN_ID: poktroll
          ENDPOINT: https://testnet-validated-validator-rpc.poktroll.com
        continue-on-error: true
        run: |
          trap 'echo "Failed running tests"' ERR
          docker run --name testing -e CHAIN_ID -e ENDPOINT pocket-network/pocketdex:test test
