name: CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - closed
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    name: 'Check Draft State'
    if: ${{ github.event.pull_request.draft != true }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.pull_request.draft != true }}
          echo "Pull Request is not draft, this workflow need continue."

  on-host:
    name: 'Host'
    uses: './.github/workflows/ci-host.yml'
    needs: draft
    secrets: inherit

  on-docker:
    name: 'Docker'
    uses: './.github/workflows/ci-docker.yml'
    needs: draft
    secrets: inherit
