name: CI
on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  on-host:
    name: 'CI on Host'
    uses: './.github/workflows/ci-host.yml'
    secrets: inherit

  on-docker:
    name: 'CI on Docker'
    uses: './.github/workflows/ci-docker.yml'
    secrets: inherit
