name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      # production mode
      - name: Build Production
        uses: docker/build-push-action@v6
        with:
          file: docker/node.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CI=true
            NODE_ENV=production
            WATCH=false
            ENDPOINT=http://proxy:26657
            CHAIN_ID=poktroll

      # develop mode
      - name: Build Develop
        uses: docker/build-push-action@v6
        with:
          file: docker/node.dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CI=true
            NODE_ENV=develop
            WATCH=true
            ENDPOINT=http://proxy:26657
            CHAIN_ID=poktroll

# TODO: run test on docker container create from the image with WATCH=true
# because WATCH=true will add the devDependencies, avoiding any CI env issues.

#      - name: Run tests with Subquery Node
#        run: subql-node-cosmos test -f ${{ github.workspace }}
